# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: Default

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: UiPathPack@4
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: 'C:\Users\serban.mocanu\Downloads\UIPCLI - Andreea\UIPCLI\UIPCLI'
    outputType: 'Tests'
    splitOutput: false
    orchestratorConnection: 'Orchestrator_Connection'
    outputPath: '$(Build.ArtifactStagingDirectory)\Output'
    traceLevel: 'Information'